baseURL = 'https://based-mathematics.netlify.app/'
languageCode = 'en-us'
title = 'Based Mathematics'
description = "Provide a simple and free online Mathematics Problem Book"
googleAnalytics = "G-YEM3NYBBCT"

theme = 'lugo'

[params]
  favicon = "favicon.svg"
  stylesheet = "/style.css"
  indexarticles = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
